from pydantic import BaseModel, Field
from typing import List, Dict

class OutlineStructure(BaseModel):
    abstract: str = Field(..., description="Abstract of the paper")
    introduction_brief_overview: str = Field(..., description="Brief overview of the topic")
    introduction_key_points: List[str] = Field(..., description="Key points to be covered")
    introduction_background: str = Field(..., description="Background information and context of the research")
    introduction_problem_statement: str = Field(..., description="Statement of the research problem or question")
    introduction_objectives: List[str] = Field(..., description="Research objectives and aims")
    main_points: Dict[str, Dict[str, List[str]]] = Field(..., description="Main topics and their subpoints for the body of the paper")
    conclusion_summary: str = Field(..., description="Summary of key findings")
    conclusion_implications: str = Field(..., description="Implications of the research")

class InitialResearch(BaseModel):
    abstract: str = Field(..., description="Abstract of the paper")
    introduction_overview: str = Field(..., description="Brief overview of the introduction")
    introduction_body: str = Field(..., description="Introduction of the copy")
    introduction_background: str = Field(..., description="Background information and context")
    introduction_problem_statement: str = Field(..., description="Statement of the research problem")
    introduction_key_points: List[str] = Field(..., description="Key points covered in the introduction")
    introduction_objectives: List[str] = Field(..., description="Research objectives and aims")
    main_points: Dict[str, Dict[str, List[str]]] = Field(..., description="Main topics and their subpoints for the body of the paper")
    conclusion_summary: Dict[str, str] = Field(..., description="Detailed conclusion summary in multiple parts")
    conclusion_implications: str = Field(..., description="Implications of the research")
    research_references: Dict[str, str] = Field(..., description="References in APA format")

class CaseStudy(BaseModel):
    case_study_background: str = Field(..., description="Background of the case study")
    case_study_problems: List[str] = Field(..., description="Problems that accompanied the background")
    case_study_goals: List[str] = Field(..., description="The goals that needed to be achieved")
    case_study_implementation: List[str] = Field(..., description="How was the topic in question implemented to achieve the goals")
    case_study_body: str = Field (..., description="Body for the case study")
    case_study_results: str = Field(..., description="What were the results of implementing the topic in question")
    case_study_references: Dict[str, str] = Field(..., description="References in APA format")

class InitialReferenceChecker(BaseModel):
    abstract: str = Field(..., description="Abstract of the paper")
    introduction_overview: str = Field(..., description="Brief overview of the introduction")
    introduction_body: str = Field(..., description="Introduction of the copy")
    introduction_background: str = Field(..., description="Background information and context")
    introduction_problem_statement: str = Field(..., description="Statement of the research problem")
    introduction_key_points: List[str] = Field(..., description="Key points covered in the introduction")
    introduction_objectives: List[str] = Field(..., description="Research objectives and aims")
    main_points: Dict[str, Dict[str, List[str]]] = Field(..., description="Main topics and their subpoints for the body of the paper")
    case_study_background: str = Field(..., description="Background of the case study")
    case_study_problems: List[str] = Field(..., description="Problems that accompanied the background")
    case_study_goals: List[str] = Field(..., description="The goals that needed to be achieved")
    case_study_implementation: List[str] = Field(..., description="How was the topic in question implemented to achieve the goals")
    case_study_results: str = Field(..., description="What were the results of implementing the topic in question")
    conclusion_summary: Dict[str, str] = Field(..., description="Detailed conclusion summary in multiple parts")
    conclusion_implications: str = Field(..., description="Implications of the research")
    references: Dict[str, str] = Field(..., description="References in APA format")

class PeerReviewFeedback(BaseModel):
    strengths: List[str] = Field(..., description="Strengths of the research")
    weaknesses: List[str] = Field(..., description="Weaknesses or areas for improvement")
    suggestions: List[str] = Field(..., description="Suggestions for addressing weaknesses")
    overall_assessment: str = Field(..., description="Overall assessment of the research")
    
class MainResearch(BaseModel):
    abstract: str = Field(..., description="Abstract of the paper")
    introduction_overview: str = Field(..., description="Brief overview of the introduction")
    introduction_body: str = Field(..., description="Introduction of the copy")
    introduction_background: str = Field(..., description="Background information and context")
    introduction_problem_statement: str = Field(..., description="Statement of the research problem")
    introduction_key_points: List[str] = Field(..., description="Key points covered in the introduction")
    introduction_objectives: List[str] = Field(..., description="Research objectives and aims")
    main_points: Dict[str, Dict[str, List[str]]] = Field(..., description="Main topics and their subpoints for the body of the paper")
    main_points_context: Dict[str, Dict[str, str]] = Field(..., description="Context for the main topics for body of the paper")
    main_subpoints_body: Dict[str, Dict[str, str]] = Field(..., description="Detailed explanation for the subpoints, and supporting information for each main topic")
    case_study_background: str = Field(..., description="Background of the case study")
    case_study_problems: List[str] = Field(..., description="Problems that accompanied the background")
    case_study_goals: List[str] = Field(..., description="The goals that needed to be achieved")
    case_study_implementation: List[str] = Field(..., description="How was the topic in question implemented to achieve the goals")
    case_study_results: str = Field(..., description="What were the results of implementing the topic in question")
    conclusion_summary: Dict[str, str] = Field(..., description="Detailed conclusion summary in multiple parts")
    conclusion_implications: str = Field(..., description="Implications of the research")
    references: Dict[str, str] = Field(..., description="References in APA format")